Description:
  Momodu Afegbua - Cloud DevOps Engineer Nanodegree - Capstone - April 2020
  Cluster configuration for the EKS
  
Parameters:
  StackName:
    Type: String
    Description: Name that will be prefixed to resource names.

Resources:
  EksServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - eks.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
        
  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Version: '1.15'
      RoleArn: !GetAtt EksServiceRole.Arn
      ResourcesVpcConfig:
        SecurityGroupIds:
        - Fn::ImportValue:
            !Sub ${StackName}-CLUSTER-SG
        SubnetIds:
            Fn::Split:
                - ","
                - Fn::ImportValue:
                      Fn::Sub: ${StackName}-SUBNETS
Outputs:
  RoleArn:
    Description: The role that Amazon EKS will use to create AWS resources for Kubernetes clusters
    Value: !GetAtt EksServiceRole.Arn
    Export:
      Name: !Sub ${StackName}-EKS-RoleArn
      
  EksId:
    Description: The EKS id.
    Value: !Ref EKSCluster
    Export: 
        Name: !Sub ${StackName}-EKS
